import type { Metadata } from "next";
import Link from "next/link";
import { site } from "@/lib/site";

export const metadata: Metadata = {
  title: "Terms of Use",
  description: `Terms of use for the free client-side developer utilities provided by ${site.name}.`,
  alternates: { canonical: "/terms" },
  openGraph: {
    type: "website",
    siteName: site.name,
    title: `Terms of Use · ${site.name}`,
    description: `Terms of use for the free client-side developer utilities provided by ${site.name}.`,
    url: `${site.url}/terms`,
    locale: "en_US",
  },
};

const updated = "September 2026";

function Section({ n, title, children }: { n: string; title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="text-lg font-semibold text-ink">
        {n}. {title}
      </h2>
      <div className="mt-2 space-y-3">{children}</div>
    </section>
  );
}

export default function TermsPage() {
  return (
    <div className="mx-auto w-full max-w-3xl px-4 py-10 md:px-6 md:py-14">
      <h1 className="text-2xl font-bold tracking-tight text-ink md:text-3xl">Terms of Use</h1>
      <p className="mt-2 text-sm text-ink-3">Last updated: {updated}</p>

      <div className="mt-8 space-y-8 text-[15px] leading-7 text-ink-2">
        <Section n="1" title="Acceptance of these terms">
          <p>
            Welcome to {site.name}. By accessing or using {site.url} you agree to be bound by these
            Terms of Use, our{" "}
            <Link href="/privacy" className="font-medium text-accent">
              Privacy Policy
            </Link>{" "}
            and any additional terms referenced here. If you do not agree with any part of these
            terms, please stop using the service.
          </p>
        </Section>

        <Section n="2" title="About the service">
          <p>
            {site.name} provides a collection of free utility applications for software developers,
            DevOps engineers and IT professionals, including JSON formatting, TypeScript type
            generation, Base64 encoding, cron expression building, hash generation and regex
            testing. All tools run entirely in your browser (client-side) and do not require an
            account or registration.
          </p>
        </Section>

        <Section n="3" title="Use of the tools">
          <p>
            You may use the tools free of charge for personal, academic and professional purposes.
            You agree not to: (a) use the tools to process unlawful, infringing or malicious data;
            (b) attempt to disrupt, overload, reverse engineer or otherwise interfere with the
            service; (c) use the tools to generate or distribute spam, malware or harmful content;
            or (d) resell, scrape or commercially exploit the service without our prior written
            consent.
          </p>
        </Section>

        <Section n="4" title="Processing of your data — disclaimer">
          <p>
            The tools process data locally, within your browser. {site.name} does not receive,
            upload, store or log the content you process. Consequently, we cannot be responsible
            for any loss, damage or unintended disclosure arising from how you handle your own
            data, including its transmission over your own network, or from the use of your
            device&apos;s processing capabilities.
          </p>
        </Section>

        <Section n="5" title="Accuracy of output">
          <p>
            We work to keep every utility correct and reliable, but output is generated for your
            convenience and may contain errors. It is your responsibility to validate, test and
            review any code, configuration, hash, schema or other result before adopting it in
            production environments, automated systems or security-critical contexts. Never use
            hashes or encoded outputs as a security control without independent verification.
          </p>
        </Section>

        <Section n="6" title="Intellectual property">
          <p>
            The site design, text, logos, trademarks and the underlying software of {site.name} are
            our property or the property of their respective owners and are protected by
            applicable intellectual property laws. Output generated by the tools belongs to you and
            may be used freely in your projects. Third-party trademarks mentioned on this site
            belong to their respective owners and are referenced only for identification purposes.
          </p>
        </Section>

        <Section n="7" title="Advertising and affiliates">
          <p>
            The site displays advertising through third-party partners, including Google AdSense,
            to keep the tools free. We may also include affiliate links to cloud, hosting and
            developer tool providers. Clicking an advertisement or affiliate link may result in a
            commission for us at no additional cost to you and may lead you to third-party sites
            governed by their own terms and privacy policies, for which we are not responsible.
          </p>
        </Section>

        <Section n="8" title="No warranty">
          <p>
            The service is provided &quot;as is&quot; and &quot;as available&quot;, without
            warranties of any kind, whether express or implied, including implied warranties of
            merchantability, fitness for a particular purpose and non-infringement. We do not
            warrant that the service will be uninterrupted, error-free, secure or always available.
          </p>
        </Section>

        <Section n="9" title="Limitation of liability">
          <p>
            To the maximum extent permitted by applicable law, {site.name} and its contributors are
            not liable for any indirect, incidental, special, consequential or punitive damages, or
            any loss of profits, data, goodwill or business opportunities, arising out of or in
            connection with the use of, or inability to use, the service, even if advised of the
            possibility of such damages.
          </p>
        </Section>

        <Section n="10" title="Third-party services">
          <p>
            The service may integrate or link to third-party products, analytics and advertising
            networks. We do not control those third parties and accept no responsibility for their
            content, availability, practices or policies. Your interaction with them is subject to
            their own terms and privacy policies.
          </p>
        </Section>

        <Section n="11" title="Changes to the service and these terms">
          <p>
            We may modify, expand, deprecate or discontinue any tool, feature or part of the
            service at any time, with or without notice. We may also revise these Terms of Use;
            the updated version will apply as of its &quot;Last updated&quot; date. Continued use
            of the service after changes constitutes acceptance of the revised terms.
          </p>
        </Section>

        <Section n="12" title="Governing law and disputes">
          <p>
            These terms are governed by the laws of Brazil. The parties submit to the exclusive
            jurisdiction of the competent courts of Brazil for any dispute arising from these
            terms, without prejudice to mandatory consumer-protection rules that may apply where
            you reside.
          </p>
        </Section>

        <Section n="13" title="Contact">
          <p>
            Questions about these terms? Write to{" "}
            <a href={`mailto:${site.legalEmail}`} className="font-medium text-accent">
              {site.legalEmail}
            </a>{" "}
            or use the{" "}
            <Link href="/contact" className="font-medium text-accent">
              Contact page
            </Link>
            .
          </p>
        </Section>
      </div>

      <p className="mt-10 text-sm text-ink-3">
        See also the{" "}
        <Link href="/privacy" className="font-medium text-accent">
          Privacy Policy
        </Link>
        .
      </p>
    </div>
  );
}